### ISSUE TITLE
Menu not scrollable on mobile or desktop

### ISSUE THREAD

**Issue by berndklb** [vaadin/vaadin-app-layout-flow#110]
If there are more menu items as space in the navbar. The navbar is not scrollable with the Material Theme.

![grafik](https://user-images.githubusercontent.com/4936361/63322724-65764700-c324-11e9-946d-822fd11a2e5d.png)
If we add these css settings, it is scrollable, but doesn't show the arrows for scroll left / right.

![grafik](https://user-images.githubusercontent.com/4936361/63322775-7fb02500-c324-11e9-953e-ae18c89eb578.png)

To reproduce you can check out these small example:
https://github.com/berndklb/vaadin-bugs.git

**Comment by alvarezguille** [comment]
The reason why the back and forward buttons are not shown and the tabs are not scrollable is that Tabs width is undefined.
Setting `width` or `max-width` for tabs will fix the issue.
`tabs.setWidthFull();` or `tabs.getElement().getStyle().set("max-width", "100%");` in `private Tabs createMenuTabs()` should do the trick

**Comment by berndklb** [comment]
@alvarezguille Thanks! That works for the touch optimized mobile menu. This is also working for the normal desktop menu, but when I add a branding / App-Name to the desktop menu it breaks again. Scrolling isn't possible. And for the mobile version, the bottom menu is out of the visible area.

And if I try to hide the branding for a mobile device like in the Lumo-Theme I have to add e. g. 
`@CssImport(value = "./styles/menu.css", themeFor = "vaadin-app-layout")`

`
  @media only screen and (max-width: 700px) {
	.hide-on-mobile {
		display: none;
	}
	
	vaadin-app-layout {
		--_vaadin-app-layout-navbar-offset-size: 0px;
	}
	
	[part="navbar"] {
		padding: 0px;
		box-shadow: none;
	}
       [part="navbar"] ::slotted(vaadin-tabs) {
    	max-width: 100% !important;
    }

	[part="navbar"] ::slotted(.hide-on-mobile) {
    	display: none;
    }

    [part="navbar"]::after {
    	content: none;
	}
}`
With branding => no scrolling
![grafik](https://user-images.githubusercontent.com/4936361/63343416-29f07280-c34e-11e9-9784-5a4970fda8c5.png)

I updated the mentioned bugfix branch

**Comment by alvarezguille** [comment]
That's the exact case of the full stack starter Bakery (demo here)[https://bakery-flow.demo.vaadin.com/] you can download the latest version from https://vaadin.com/start/latest/full-stack-spring

It also has branding content and tabs are centered 

In desktop it has a `max-width` of 65% so that it's centered and there is room for branding
![image](https://user-images.githubusercontent.com/9820084/63345522-9cb41a80-c35b-11e9-8c31-d40535557d4a.png)

In narrow viewports the `max-width` is 100% and the branding Span is hidden
![image](https://user-images.githubusercontent.com/9820084/63345757-206e0700-c35c-11e9-9ffe-429cae8e1ec0.png)

In mobile `max-width` is still 100%
![image](https://user-images.githubusercontent.com/9820084/63345870-6f1ba100-c35c-11e9-8b42-8612b9b5b2c4.png)

**Comment by berndklb** [comment]
@alvarezguille  Is there a reason, why this behavior is not implemented as default? So for now I have to check bakery example app, find the correct styles in shared-styles.js and copy these to my project, so the menu items can be scrollable and the branding will be visible / hidden.
With Vaadin 13 it all come out of the box. For me it is okay to close the ticket. But you have to agree, that this is not the way the app-layout should work.
But thanks for your fast response.

**Comment by alvarezguille** [comment]
@berndklb thanks for the feedback
The main reason for the change was that we want AppLayout to be just the layout, that's why the Menu implementation was removed. Also we didn't want it to be opinionated with Tabs for implementation of the menu, especially now with the Drawer section.
This resulted in a breaking change, and we added documentation for the (migration to AppLayout 2.0)[https://vaadin.com/docs/v14/flow/v14-migration/app-layout-v2-migration-guide.html], but we are probably missing some details still.
We are also considering to add helpers for creating the menu in #96.
