### ISSUE TITLE
Simple spring-boot App using AppLayout hangs up server connection

### ISSUE THREAD

**Issue by enver-haase** [vaadin/vaadin-app-layout-flow#146]
Please see attached mini project and read its README.md file.

If I use my own simple RouterLayout things are working, but I am losing the server connection between the client and the server using AppLayout instead.

[foo-dashboard.tar.gz](https://github.com/vaadin/vaadin-app-layout-flow/files/4737350/foo-dashboard.tar.gz)

User / Password is 'user'/'user' by the way, see Application.yml

**Comment by alvarezguille** [comment]
The same can be reproducing by adding a ComboBox
`layout.add(new ComboBox<>("label", "item 0", "item 1", "item 2", "item 3", "item 4"));`
And is not related to AppLayout. 
The issue is caused by missing spring security configuration.
Take a look at this tutorial about setting up [Spring Security for Vaadin applications](https://vaadin.com/learn/tutorials/securing-your-app-with-spring-security/setting-up-spring-security)
