### ISSUE TITLE
The menu selection is not updated according to navigation

### ISSUE THREAD

**Issue by TatuLund** [vaadin/vaadin-app-layout-flow#73]
The selected menu item is not updated when navigating either programmatically or via url. 

I would expect the right menu item be highlighted, i.e. same menu item whose content is shown.

You can workaround this issue by having AfterNavigationObserver in the layout where you have the app layout, something like:

```
public class MainLayout extends AppLayout implements RouterLayout, AfterNavigationObserver {

        private AppLayoutMenu menu = createMenu();

	public MainLayout() {
           ...
        }

	@Override
	public void afterNavigation(AfterNavigationEvent event) {
		menu.getMenuItemTargetingRoute(event.getLocation().getPath()).ifPresent(
                          menuItem -> menu.selectMenuItem(menuItem));		
	}
}
```

**Comment by ugurdoksan** [comment]
I can not understand that why this issue still has not been solved. Really unbelievable!

**Comment by alvarezguille** [comment]
This issue is related to App Layout 1.x that includes implementation for AppLayoutMenu. In this case the recommendation is to extend `AbstractAppRouterLayout` which already implements  `RouterLayout` and updates the selected menu after navigation
https://github.com/vaadin/vaadin-app-layout-flow/blob/1.1.1/vaadin-app-layout-flow/src/main/java/com/vaadin/flow/component/applayout/AbstractAppRouterLayout.java#L77-L93

For information about having this behavior in App Layout 2.x that doesn't include implementation for `AppLayoutMenu` check the [migration guide](https://vaadin.com/docs/v14/flow/v14-migration/app-layout-v2-migration-guide.html) and this [forum post](https://vaadin.com/forum/thread/17756493/17758645). Helpers for creating menu and keeping selection up to date will be considered as part of #96
